# Generated by Django 4.1.3 on 2023-01-13 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessengerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('MobileNumber', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('BirthDate', models.DateField(verbose_name='BirthDate')),
                ('CreateDate', models.DateField(default=datetime.date.today, verbose_name='CreateDate')),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
