# Generated by Django 4.1.3 on 2023-01-15 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessengerApp', '0002_newcustomers_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('MobileNumber', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('BirthDate', models.DateField(verbose_name='BirthDate')),
                ('CreateDate', models.DateField(default=datetime.date.today, verbose_name='CreateDate')),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='NewCustomers',
        ),
    ]
